// let i = 10;
// let sum = 0;

// while (i < 6) {
//     sum += i
//     i++    
// }

// console.log({sum});

// do {
//     sum += i
//     i++   
// } while (i < 6);
// console.log({sum},{i});

// let i = +prompt('Bir sayı giriniz : ')

// while (isNaN(i)) {
//     i = +prompt('Bir sayı giriniz : ')
    

    
// }


// console.log('Bir sayı girdiniz');
// let i;
// do {
//     i = +prompt('Bir sayı giriniz : ')
// } while (isNaN(i));

// console.log(`Girilen değer ${i}`);

// let i = 0;

// while (true) {
//     console.log(i);
//     i++
//     if (i == 6) break;
// }


let i = 0;

for (i; i < 10;) {
    console.log(i);
    i++
}

console.log({i});